### ISSUE TITLE
Template - Customers - Validation

### ISSUE THREAD

**Issue by valentinajemuovic** [atomiv/atomiv-java#11]
@jelenamitrovic980 for all the REST API methods done in #3, could you implement validation:
* firstName must not be null or empty
* lastName must not be null or empty

**Comment by jelenamitrovic980** [comment]
@valentinacupac  
do I have to have a special customerController for validation?

**Comment by valentinajemuovic** [comment]
@jelenamitrovic980 there is only one controller, i.e. CustomerController, so you don't need to make any new controllers... Trying finding tutorials: Java Spring Boot REST API validation

**Comment by jelenamitrovic980** [comment]
@valentinacupac 
Spring Boot Rest API Validation with Hibernate Validator  https://www.youtube.com/watch?v=pjA9Pc7aTic
May I have more different methods Get, Post, Put in the Controller then?

**Comment by valentinajemuovic** [comment]
@jelenamitrovic980 yes you can do it like they showed in the tutorial (but it would be done for existing Get, Post, Put methods, i.e. there won't be new methods)
