### ISSUE TITLE
Template - Customers - Domain

### ISSUE THREAD

**Issue by valentinajemuovic** [atomiv/atomiv-java#3]
@jelenamitrovic980 as the first activity for the template project (see the folder template.web.restapi inside this repo) could you implement these operations for customers. 

Customer has the following data: 

* id
* firstName
* lastName

**Comment by jelenamitrovic980** [comment]
@valentinacupac  should the tapy of ID be Long?

**Comment by valentinajemuovic** [comment]
@jelenamitrovic980 yes, it should be long.
